[package]
name = "my-service-bus-shared"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "*"
prost = "0.8.0"
prost-types = "0.8.0"
chrono = "0.4.19"
tokio = { version = "*", features = ["full"] }
