[package]
name = "my-service-bus-shared"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-extensions = { branch = "main", git = "https://github.com/MyJetTools/rust-extensions.git" }


zip = "*"
prost = "0.9.0"
prost-types = "0.9.0"
chrono = "0.4.19"
tokio = { version = "*", features = ["full"] }
